<h3>Roles</h3>
<table class="table table-hover table-bordered table-condensed">
	<thead>
	<tr>
		<th>ID</th>
		<th>Role ID</th>
		<th>Is Default</th>
		<th>Parent ID</th>
		<th>Edit</th>
		<th>Delete</th>
	</tr>
	</thead>
	<tbody>
		<?php foreach($roles as $role):?>
		<tr>
			<td><?php echo $role->id ?></td>
			<td><?php echo $role->role_id ?></td>
			<td><?php echo $role->is_default ?></td>
			<td><?php echo $role->parent_id ?></td>
			<td><a class="btn" href="<?php echo $this->url('zfcadmin/zfcroleadmin', array('action'=>'edit','id'=>$role->id));?>">Edit</a> </td>
			<td><a class="btn" href="<?php echo $this->url('zfcadmin/zfcroleadmin', array('action'=>'delete','id'=>$role->id));?>">Delete</a> </td>
		</tr>
		<?php endforeach;?>
	</tbody>
</table>
<a class="btn" href="<?php echo $this->url('zfcadmin/zfcroleadmin', array('action'=>'add'));?>">Add Role</a> 